service: core-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

package:
  include:
    - src/**
  exclude:
    - node_modules/typescript/**
    - test/**

functions:
  app:
    handler: src/serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
